### ISSUE TITLE
pull requests directly onto dev

### ISSUE THREAD

**Issue by lheagy** [simpeg/discretize#78]
Similar to simpeg/simpeg#651: To speed up getting features live into discretize, we could do pull requests directly onto master. 

## Impacts
- your features are rapidly live to the world!
- pull requests should be small and focussed
- pull request notes will be used as the release notes and so should contain sufficient detail to describe the changes, any breaks in backwards compatibility, etc.  

## TODO's
- [x] switch main branch to master on github
- [x] ensure dev and master synced
- [x] change base of current pr's onto dev to master
- [x] delete dev branch
- [x] update travis to remove deployment sequence from dev 

## Timeline
We can do this as soon as #73 is in. Are there any concerns about doing this soon? cc @rowanc1, @grosenkj, @sgkang, @thast, @fourndo. Can you please give a 👍 or 👎?

**Comment by lheagy** [comment]
closed with #79

**Comment by leouieda** [comment]
Hi all, just a comment regarding the "release notes from PR" and "small PRs". I've been doing these in conjunction with squash merges for PRs and I like it a lot. When I merge the PR, github will squash all commits down to a single one and allows you to edit the commit message. I copy and edit the initial PR description as the message. This gets rid of trial-and-error commits in the PR or commits that result in broken tests. It also allows me to edit bad messages from newer users (or my own). It also gives a bit of freedom when I just want to commit half finished work and don't have the time for a long good message.
